Spring hw 3 solution
AnatolyNz/spring-boot-web-dto pull request #1
Opened 2024-01-12 08:33 UTC by AnatolyNz

2024-01-12 10:54 UTC, okuzan requested changes

2024-01-12 10:54 UTC, okuzan commented on src/main/java/mate/academy/WebDtoApplication.java
> +public class WebDtoApplication {
```suggestion
public class BookStoreApplication {
```
unusual name for the main class

2024-01-12 10:54 UTC, okuzan commented on mvnw
> +    # and check out the mate.academy.repository with auto CRLF management
mvn files shouldn't be committed to the repo

2024-01-12 10:54 UTC, okuzan commented on pom.xml
> +        <relativePath/> <!-- lookup parent from repository -->
```suggestion
        <relativePath/> 
```

2024-01-12 10:54 UTC, okuzan commented on src/main/java/mate/academy/repository/BookDaoImpl.java
> +        }
```suggestion
        } catch (Exception e) {
        throw new RuntimeException("Can't get book by id from DB: " + id, e);
    }
```

2024-01-13 16:52 UTC, Ivan95kos approved these changes
Great job, with a minor comment

2024-01-13 16:52 UTC, Ivan95kos commented on src/main/java/mate/academy/controller/BookController.java
> +    public List getAll() {
It is bad practice, you need to set the Type
```suggestion
    public List<BookDto> getAll() {
```

2024-01-17 08:23 UTC, closed without merging