Spring hw 14 solution
AnatolyNz/spring-boot-web-dto pull request #23
Opened 2024-03-26 08:52 UTC by AnatolyNz

2024-03-26 12:36 UTC, MAMentorFX requested changes

2024-03-26 12:36 UTC, MAMentorFX commented on src/main/java/mate/academy/BookStoreApplicationJwt.java
> +
```suggestion
```

2024-03-26 12:36 UTC, MAMentorFX commented on src/main/java/mate/academy/mapper/ShoppingCartMapper.java
> +    @Mapping(target = "cartItems", source = "cartItems")
```suggestion
```

2024-03-26 12:36 UTC, MAMentorFX commented on src/main/java/mate/academy/repository/ShoppingCartRepository.java
> +
```suggestion
```

2024-03-26 12:36 UTC, MAMentorFX commented on src/main/java/mate/academy/controller/ShoppingCartController.java
> +    @PreAuthorize("hasAuthority('ROLE_USER')")
Each controller's method annotations are ordered differently, please, be consistent

2024-03-26 12:36 UTC, MAMentorFX commented on src/main/java/mate/academy/model/CartItem.java
> +    @EqualsAndHashCode.Exclude
Use @ToString(exclude = {...}) @EqualsAndHashCode(exclude = {"bar"}) instead

2024-03-26 12:36 UTC, MAMentorFX commented on src/main/java/mate/academy/service/ShoppingCartService.java
> +                            CartItemQuantityRequestDto qtyToSubtract);
Services shouldn't work with Authentication. Pass User to services

2024-03-26 12:36 UTC, MAMentorFX commented on src/main/java/mate/academy/service/ShoppingCartServiceImpl.java
> +    private final UserRepository userRepository;
order fields by similar functionality

2024-03-26 12:36 UTC, MAMentorFX commented on src/main/java/mate/academy/service/ShoppingCartServiceImpl.java
> +    }
You make more then one request to db, make it transactional. Do the same for each method that has more then one ewqeust

2024-03-26 12:36 UTC, MAMentorFX commented on src/main/java/mate/academy/service/ShoppingCartServiceImpl.java
> +        }
use ifPresentOrElse

2024-03-26 19:39 UTC, MAMentorFX requested changes
Very well, needs some fixes

2024-03-26 19:39 UTC, MAMentorFX commented on src/main/java/mate/academy/service/ShoppingCartServiceImpl.java
> +        User user = (User) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
No, your bussiness logic shouldn't depend on infrastructure. You need to User instead of Authefication to your Services

2024-03-26 19:39 UTC, MAMentorFX commented on src/main/java/mate/academy/service/ShoppingCartServiceImpl.java
> +        final CartItem[] cartItemToUpdate = new CartItem[1];
Don't use arrays here.

2024-03-27 18:21 UTC, MAMentorFX requested changes

2024-03-27 18:21 UTC, MAMentorFX commented on src/main/java/mate/academy/controller/ShoppingCartController.java
> +        shoppingCartService.addItemToCart(authentication, cartItemRequestDto);
Pass user istead of Authentication. Service doesn't need to work with whole Authentication object.

2024-03-27 18:21 UTC, MAMentorFX commented on src/main/java/mate/academy/service/ShoppingCartServiceImpl.java
>      }
createNewCartItem @Transactional methods can not be private. Spring won't be able to create a proper proxy

2024-03-27 18:21 UTC, MAMentorFX commented on src/main/java/mate/academy/service/ShoppingCartServiceImpl.java
>          );
In case existingCartItem is not present, you create a new one. But you don't set quantity. Why? If you need to set quantity, please just do something like this 

          `CartItem cartItem = existingCartItem.orElseGet(() -> createNewCartItem());

        cartItem.setQuantity(cartItemRequestDto.getQuantity() + cartItem.getQuantity());
        cartItemRepository.save(cartItem);`

2024-03-29 14:38 UTC, AnatolyNz commented on src/main/java/mate/academy/service/ShoppingCartServiceImpl.java
>          );
When we run cartItemRepository.save(newCartItem) it set quantity. If we use setQuantity we do duplicate quantity and quantity will in 2 time more

2024-03-29 15:41 UTC, olekskov approved these changes

2024-03-29 15:41 UTC, olekskov commented on src/main/java/mate/academy/service/ShoppingCartServiceImpl.java
> +        );
As for me in this case classical structure is more simple and readable than functional style one
```suggestion
        CartItem cartItem;
        if (existingCartItem.isEmpty) {
            cartItem = createNewCartItem(cartItemRequestDto, shoppingCart);
        } else {
           cartItem = existingCartItem.get();
           cartItem.setQuantity(cartItemRequestDto.getQuantity() + cartItem.getQuantity());
        }
        cartItemRepository.save(cartItem);
```

2024-04-10 15:26 UTC, merged