Fixed for SpringBootPractice3
AnatolyNz/spring-boot-web-dto pull request #29
Opened 2024-04-12 08:09 UTC by AnatolyNz

2024-04-12 10:38 UTC, MAMentorFX requested changes

2024-04-12 10:38 UTC, MAMentorFX commented on src/main/java/mate/academy/mapper/BookMapper.java
> +    }
remove or implement

2024-04-12 10:38 UTC, MAMentorFX commented on src/main/java/mate/academy/mapper/OrderItemMapper.java
> +    @Mapping(target = "quantity", source = "quantity")
```suggestion
```

2024-04-12 10:38 UTC, MAMentorFX commented on src/main/java/mate/academy/mapper/OrderMapper.java
> +    @Mapping(target = "total", source = "total")
```suggestion
```

2024-04-12 10:38 UTC, MAMentorFX commented on src/main/java/mate/academy/model/OrderItem.java
> +    @JoinColumn(name = "order_id", nullable = false)
use
@EqualsAndHashCode(exclude = {})
@ToString(exclude = {})
on class level

2024-04-12 10:38 UTC, MAMentorFX commented on src/main/java/mate/academy/service/CategoryServiceImpl.java
> +                .collect(Collectors.toList());
Mapstruct supports mapping collections from the box

2024-04-12 10:38 UTC, MAMentorFX commented on src/main/java/mate/academy/service/CategoryServiceImpl.java
> +    public CategoryResponseDto update(Long id, CategoryDto categoryDto) {
Transaction

2024-04-12 10:38 UTC, MAMentorFX commented on src/main/java/mate/academy/service/OrderServiceImpl.java
> +        order.setTotal(BigDecimal.valueOf(total));
use MapStruct

2024-04-12 10:38 UTC, MAMentorFX commented on src/main/java/mate/academy/service/OrderServiceImpl.java
> +                    return orderItemRepository.save(orderItem);
mapsctruct

2024-04-12 10:38 UTC, MAMentorFX commented on src/main/java/mate/academy/service/OrderServiceImpl.java
> +                .toList();
mapstctrct

2024-04-12 10:38 UTC, MAMentorFX commented on src/main/java/mate/academy/service/OrderServiceImpl.java
> +                .toResponseDto((OrderItem) order.getOrderItems());
why we need casting?

2024-04-12 10:38 UTC, MAMentorFX commented on src/main/java/mate/academy/service/ShoppingCartServiceImpl.java
> +    private ShoppingCart registerNewShoppingCart(User user) {
private methods after public ones

2024-04-13 09:32 UTC, AnatolyNz commented on src/main/java/mate/academy/service/OrderServiceImpl.java
> +                .toResponseDto((OrderItem) order.getOrderItems());
Without casting I have error.

2024-04-13 17:06 UTC, olekskov requested changes

2024-04-13 17:06 UTC, olekskov commented on src/main/java/mate/academy/service/OrderServiceImpl.java
> +        Order order = orderMapper.toModel(orderRequestDto);
I cannot see reason why shopping cart should be mapped to OrderRequestDto to instantly remapped to Order

just make constructor for Order that accepts ShoppingCart
```suggestion
        Order order = new Order(shoppingCart);
```

2024-04-13 17:06 UTC, olekskov commented on src/main/java/mate/academy/service/OrderServiceImpl.java
> +                    OrderItem orderItem = orderItemMapper.toEntity(orderItemDto);
same
```suggestion
                    OrderItem orderItem = new OrderItem(cartItem);
```

2024-04-14 10:48 UTC, okuzan approved these changes

2024-04-15 06:59 UTC, merged