Spring hw 18 solution
AnatolyNz/spring-boot-web-dto pull request #33
Opened 2024-05-27 10:31 UTC by AnatolyNz

2024-05-27 12:41 UTC, okuzan requested changes
Good job, clean code :) minor remarks

2024-05-27 12:41 UTC, okuzan commented on src/test/java/mate/academy/controller/BookControllerTest.java
> +@AutoConfigureMockMvc // Automatically configure MockMvc
```suggestion
@AutoConfigureMockMvc
```
remove GPT comments :))

2024-05-27 12:41 UTC, okuzan commented on src/test/java/mate/academy/repository/BookRepositoryTest.java
> +    }, executionPhase = Sql.ExecutionPhase.AFTER_TEST_METHOD)
setup is the same for each method, extract to a class level

2024-05-27 12:41 UTC, okuzan commented on src/test/java/mate/academy/repository/CategoryRepositoryTest.java
> +            """)
```suggestion
    @DisplayName("Get category by valid ID")
```
fix everywhere for short names

2024-05-27 12:41 UTC, okuzan commented on src/test/java/mate/academy/service/CategoryServiceTest.java
> +    public void testFindAll_ValidSearchParameters_ShouldReturnListOfCategories() {
```suggestion
    public void findAll_ValidSearchParameters_ShouldReturnListOfCategories() {
```

2024-05-27 12:41 UTC, okuzan commented on src/test/java/mate/academy/service/CategoryServiceTest.java
> +    public void testUpdateById_WithNotValidCategoryId_ShouldThrowException() {
```suggestion
    public void updateById_WithNotValidCategoryId_ShouldThrowException() {
```
unify naming

2024-05-30 07:09 UTC, Elena-Bruyako requested changes
Good job! let's consider some comments.

2024-05-30 07:09 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/BookServiceImpl.java
>          Book book = bookMapper.toModel(bookWithoutId);
It's better to 
```suggestion
        Book book = bookRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(getNotFoundMessage(id)));
        bookMapper.updateBookFromDto(bookDto, book);
```
where in BookMapper
`void updateBookFromDto(CreateBookRequestDto book, @MappingTarget Book entity);`

2024-05-30 07:09 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/BookServiceImpl.java
>          Book book = bookMapper.toModel(bookWithoutId);
Should we set categories here? 
```
book.setCategories(categoriesIdToCategories(bookDto.categoriesId()));
return bookMapper.toDto(bookRepository.save(book));
```

2024-05-30 07:09 UTC, Elena-Bruyako commented on src/test/java/mate/academy/repository/BookRepositoryTest.java
> +        Assertions.assertEquals(expected.getId(), actual.getId());
Let's use import static
```suggestion
        assertEquals(expected.getId(), actual.getId());
```
Check all places

2024-05-31 12:03 UTC, MentorMateAcademy requested changes

2024-05-31 12:03 UTC, MentorMateAcademy commented on src/main/java/mate/academy/dto/CreateBookRequestDto.java
>      @Min(0)
```suggestion
    @Positive
```

2024-05-31 12:03 UTC, MentorMateAcademy commented on src/main/java/mate/academy/dto/CreateBookRequestDto.java
>      @Min(0)
Better use this anno

2024-05-31 12:03 UTC, MentorMateAcademy commented on src/main/java/mate/academy/repository/book/BookRepository.java
>  }
Method save already exists in JpaRepository, check others
![image](https://github.com/AnatolyNz/spring-boot-web-dto/assets/170757042/48ed7b1b-39e3-4fc9-9ef6-26c4334ccda5)

2024-05-31 12:03 UTC, MentorMateAcademy commented on src/test/java/mate/academy/controller/BookControllerTest.java
> +    }
![image](https://github.com/AnatolyNz/spring-boot-web-dto/assets/170757042/367a0861-3583-4ed6-943d-ecef4c1b75ca)

2024-05-31 12:03 UTC, MentorMateAcademy commented on src/test/java/mate/academy/controller/BookControllerTest.java
> +    }
when and then use in correct places

2024-05-31 12:03 UTC, MentorMateAcademy commented on src/test/java/mate/academy/controller/BookControllerTest.java
> +                .setIsbn("ISBN-908765").setPrice(BigDecimal.valueOf(250)).setCategoryIds(Set.of()));
write better ib stack and Strings what you use write to constants and reuse it

2024-05-31 12:03 UTC, MentorMateAcademy commented on src/test/java/mate/academy/controller/CategoryControllerTest.java
> +                .setCoverImage("image3.jpg"));
Use list.of and better create this templates in private methods or util class

2024-05-31 12:03 UTC, MentorMateAcademy commented on src/test/java/mate/academy/repository/BookRepositoryTest.java
> +        assertEquals(expected.isDeleted(), actual.isDeleted());
You don`t need to compare every field if you can compare this objects

2024-05-31 12:03 UTC, MentorMateAcademy commented on src/test/java/mate/academy/service/BookServiceTest.java
> +    private BookServiceImpl bookService;
Place InjectMocks after Mock

2024-05-31 12:03 UTC, MentorMateAcademy commented on src/test/java/mate/academy/service/BookServiceTest.java
> +        // Assertions
Don`t need this comments for code

2024-05-31 12:03 UTC, MentorMateAcademy commented on src/test/java/mate/academy/service/BookServiceTest.java
> +        expected.setId(id);
use this code in start of method

2024-06-01 15:37 UTC, sarakhmen approved these changes
Good job!

2024-06-01 15:37 UTC, sarakhmen commented on src/main/java/mate/academy/repository/book/BookRepository.java
>      Optional<Book> getBookById(Long id);
do you really need your custom method for this operation? Please use OOTB methods of JpaRepository instead

2024-06-01 18:01 UTC, merged